name: Xcode Run Unit Tests in Package
description: Xcode Run Unit Tests in Package
inputs:
  platform:
    description: "Target Build Platform"
  scheme:
    description: "Xcode Scheme Name"
  retry_failed_tests:
    description: "Retry Failed Tests"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Generate Xcode Project
      run: xcodegen
      shell: bash -leo pipefail {0}
    - name: Run Unit Tests (iOS)
      run: |
        xcodebuild -scheme '${{ inputs.scheme }}' -destination 'platform=iOS Simulator,name=iPhone 15 Pro' test \
        ${{ inputs.retry_failed_tests && '-retry-tests-on-failure' || '' }}
      shell: bash -leo pipefail {0}
      if: inputs.platform == 'ios'
    - name: Run Unit Tests (macOS)
      run: |
        xcodebuild -scheme '${{ inputs.scheme }}' -sdk macosx test -allowProvisioningUpdates \
        ${{ inputs.retry_failed_tests && '-retry-tests-on-failure' || '' }}
      shell: bash -leo pipefail {0}
      if: inputs.platform == 'mac'
