name: Prepare Xcode Build
description: Prepare Xcode Build
inputs:
  branch:
    description: "Custom ref/branch to check out (required for TestFlight submission workflow; defaults to the commit of the job that triggered this workflow)"
  p12-file-development:
    description: "Development Certificate File (required for dev and release builds)"
  p12-file-development-password:
    description: "Development Certificate Password (required for dev and release builds)"
  p12-file-distribution:
    description: "Distribution Certificate File (required for release builds)"
  p12-file-distribution-password:
    description: "Distribution Certificate Password (required for release builds)"
  ssh-private-key:
    description: "Private SSH Key (required for cloud runner)"
  runner-root-password:
    description: "Root password for sudo operations"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for scripts that access multiple branches, e.g. `increment-build-number.sh`
        ref: ${{ inputs.branch || '' }}
    - name: (Local) Select Xcode Version
      id: select-xcode
      uses: FelixLisczyk-Org/GitHub-Workflows/xcode-select-version@main
      with:
        runner-root-password: ${{ inputs.runner-root-password }}
    - name: (Local) Store Original Xcode Path # for later use in `finish-xcode-build`
      run: echo "ORIGINAL_XCODE_PATH=${{ steps.select-xcode.outputs.original-xcode-path }}" >> $GITHUB_ENV
      shell: bash -leo pipefail {0}
      if: contains(runner.workspace, '/Users/runner/') == false
    - name: (Cloud) Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
      if: contains(runner.workspace, '/Users/runner/')
    - name: Allow Swift Macros to be executed
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      shell: bash -leo pipefail {0}
    - name: Import Development Certificate
      id: create_keychain
      uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ inputs.p12-file-development }}
        p12-password: ${{ inputs.p12-file-development-password }}
      if: inputs.p12-file-development != '' && inputs.p12-file-development-password != ''
    - name: Import Distribution Certificate
      uses: apple-actions/import-codesign-certs@v3
      with:
        create-keychain: false
        keychain-password: "${{ steps.create_keychain.outputs.keychain-password }}"
        p12-file-base64: ${{ inputs.p12-file-distribution }}
        p12-password: ${{ inputs.p12-file-distribution-password }}
      if: inputs.p12-file-distribution != '' && inputs.p12-file-distribution-password != ''
    - name: (Cloud) Load SSH Private Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
      if: contains(runner.workspace, '/Users/runner/') && inputs.ssh-private-key != ''
    - name: Clone Swift Packages over SSH
      run: git config --global url."git@github.com:".insteadOf "https://github.com/"
      shell: bash -leo pipefail {0}
      # This step is required for the cache actions to find the `zstd` executable in the Homebrew directory.
    - name: (Local) Add PATH to GITHUB_PATH
      run: echo $PATH >> $GITHUB_PATH
      shell: bash -leo pipefail {0}
      if: contains(runner.workspace, '/Users/runner/') == false
    - name: (Cloud) Install Build Tools
      run: brew install sourcery swiftgen xcodegen
      shell: bash -leo pipefail {0}
      if: contains(runner.workspace, '/Users/runner/')
    - name: Check if Gemfile exists
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "Gemfile"
    - name: Install fastlane
      run: bundle install
      shell: bash -leo pipefail {0}
      if: steps.check_files.outputs.files_exists == 'true'
