name: Restore Xcode Version
description: Restore the original Xcode version
inputs:
  original_xcode_path:
    description: "The original Xcode path to restore"
    required: true
  runner_root_password:
    description: "Root password for sudo operations"
    required: true
runs:
  using: "composite"
  steps:
    - name: (Local) Restore Original Xcode Version
      run: |
        echo "Restoring original Xcode version: ${{ inputs.original_xcode_path }}"
        echo "${{ inputs.runner_root_password }}" | sudo -S xcode-select -s "${{ inputs.original_xcode_path }}"
        xcodebuild -version
      shell: bash -leo pipefail {0}
      if: contains(runner.workspace, '/Users/runner/') == false
