name: Xcode Build Swift Package
description: Xcode Build Swift Package
inputs:
  platform:
    description: "Target Build Platform"
  scheme:
    description: "Xcode Scheme Name"
  retry_failed_tests:
    description: "Retry Failed Tests"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Generate Xcode Project
      run: |
        if [ -f project.yml ]; then
          xcodegen
        fi
      shell: bash -leo pipefail {0}
    - name: Resolve Swift Packages
      run: |
        if [ -f project.yml ]; then
          xcodebuild -resolvePackageDependencies
        else
          swift package resolve
        fi
      shell: bash -leo pipefail {0}
    - name: Run Unit Tests
      uses: FelixLisczyk-Org/GitHub-Workflows/xcode-test-package@main
      with:
        platform: ${{ inputs.platform }}
        scheme: ${{ inputs.scheme }}
        retry_failed_tests: ${{ inputs.retry_failed_tests }}
