name: Finish Xcode Build
description: Finish Xcode Build
inputs:
  runner-root-password:
    description: "Root password for sudo operations"
    required: true
runs:
  using: "composite"
  steps:
    - name: (Cloud) On Failure - Zip Workspace
      run: zip -r -q workspace.zip .
      shell: bash -leo pipefail {0}
      if: job.status == 'failure' && contains(runner.workspace, '/Users/runner/')
    - name: (Cloud) On Failure - Upload Workspace as Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: workspace.zip
      if: job.status == 'failure' && contains(runner.workspace, '/Users/runner/')
    - name: Cleanup Temporary Keychain Entry
      continue-on-error: true
      run: security delete-keychain signing_temp.keychain
      shell: bash -leo pipefail {0}
      if: always()
    - name: Revert Git SSH Redirect
      run: git config --global --unset url."git@github.com:".insteadOf "https://github.com/"
      shell: bash -leo pipefail {0}
      if: always()
    - name: (Local) Restore Xcode Version
      uses: FelixLisczyk-Org/GitHub-Workflows/xcode-restore-version@main
      with:
        original-xcode-path: ${{ env.ORIGINAL_XCODE_PATH }}
        runner-root-password: ${{ inputs.runner-root-password }}
      if: always()
