name: Finish Xcode Build
description: Finish Xcode Build
runs:
  using: "composite"
  steps:
    - name: (Cloud) On Failure - Zip Workspace
      run: zip -r -q workspace.zip .
      shell: bash
      if: job.status == 'failure' && contains('/home/runner', runner.temp)
    - name: (Cloud) On Failure - Upload Workspace as Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: workspace.zip
      if: job.status == 'failure' && contains('/home/runner', runner.temp)
    - name: Cleanup Temporary Keychain Entry
      run: security delete-keychain signing_temp.keychain
      shell: bash
      if: always()
    - name: Revert Git SSH Redirect
      run: git config --global --unset url."git@github.com:".insteadOf "https://github.com/"
      shell: bash
      if: always()
