name: Finish Xcode Build
description: Finish Xcode Build
inputs:
  runner_root_password:
    description: "Root password for sudo operations"
    required: true
runs:
  using: "composite"
  steps:
    - name: (Cloud) On Failure - Zip Workspace
      run: zip -r -q workspace.zip .
      shell: bash -leo pipefail {0}
      if: job.status == 'failure' && contains(runner.workspace, '/Users/runner/')
    - name: (Cloud) On Failure - Upload Workspace as Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: workspace
        path: workspace.zip
      if: job.status == 'failure' && contains(runner.workspace, '/Users/runner/')
    - name: Revert Git SSH Redirect
      run: |
        if git config --global --get url."git@github.com:".insteadOf >/dev/null 2>&1; then
          echo "Removing git SSH redirect config..."
          git config --global --unset url."git@github.com:".insteadOf "https://github.com/"
        else
          echo "Git SSH redirect config not found (already removed)"
        fi
      shell: bash -leo pipefail {0}
      if: always()
    - name: (Local) Restore Xcode Version
      uses: FelixLisczyk-Org/GitHub-Workflows/xcode-restore-version@main
      with:
        original_xcode_path: ${{ env.ORIGINAL_XCODE_PATH }}
        runner_root_password: ${{ inputs.runner_root_password }}
      if: always()
    - name: Remove [safe] section from gitconfig
      run: |
        git config --global --remove-section safe || echo "[safe] section not found"
      shell: bash -leo pipefail {0}
      if: always()
