name: Submit App
description: "Submit the latest build to App Store or TestFlight and optionally set a Git version tag."
inputs:
  platform:
    description: "Target platform (ios or mac)"
    required: true
  lane:
    description: "Fastlane lane to use (e.g., submit_to_testflight, submit_for_review)"
    required: true
  set_git_tag:
    description: "Set Git version tag"
    required: false
    default: false
    type: boolean
  git_tag_version_target:
    description: "Xcode target name for retrieving the version number"
    required: false
  git_tag_suffix:
    description: "Suffix for git tag (e.g., Release)"
    required: false
  version:
    description: "App version to submit"
    required: false
    default: ""
  build:
    description: "Build number to submit"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Submit Latest Build to App Store/TestFlight
      env:
        SUBMISSION_PLATFORM: ${{ inputs.platform }}
        SUBMISSION_LANE: ${{ inputs.lane }}
        SUBMISSION_VERSION: ${{ inputs.version }}
        SUBMISSION_BUILD: ${{ inputs.build }}
      run: |
        args=()
        if [[ "$SUBMISSION_LANE" == "submit_to_testflight" ]]; then
          args+=("publish_external:false")
        fi
        if [[ -n "$SUBMISSION_VERSION" ]]; then
          args+=("app_version:$SUBMISSION_VERSION")
        fi
        if [[ -n "$SUBMISSION_BUILD" ]]; then
          args+=("build_number:$SUBMISSION_BUILD")
        fi
        bundle exec fastlane "$SUBMISSION_PLATFORM" "$SUBMISSION_LANE" "${args[@]}"
      shell: bash -leo pipefail {0}
    - name: Set Git Version Tag
      if: ${{ inputs.set_git_tag && inputs.git_tag_version_target != '' && inputs.git_tag_suffix != '' }}
      run: |
        ./generate.sh --no-binary-cache
        bundle exec fastlane ${{ inputs.platform }} add_git_version_tag target:"${{ inputs.git_tag_version_target }}" suffix:"${{ inputs.git_tag_suffix }}"
        git push --tags
      shell: bash -leo pipefail {0}
